#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
SERVICE_NAME="vlf-gateway"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
SERVICE_USER="vlfproto"
SERVICE_GROUP="vlfproto"

INSTALL_DIR_DEFAULT="/opt/vlf-proto"
CONFIG_DIR="/etc/vlf-proto"
ENV_FILE="${CONFIG_DIR}/.env"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"
BIN_PATH="/usr/local/bin/vlf-gateway"
CERT_FILE="${CONFIG_DIR}/tls.crt"
KEY_FILE="${CONFIG_DIR}/tls.key"

REPO_URL_DEFAULT="https://github.com/skalover32-a11y/VLF-Proto.git"
REF_DEFAULT="main"
GO_VERSION_DEFAULT="1.25.1"
PROTOCOL_ID_DEFAULT="vlf-runtime/0.1"
LOG_LEVEL_DEFAULT="info"

REPO_URL="${REPO_URL_DEFAULT}"
REF="${REF_DEFAULT}"
GO_VERSION="${GO_VERSION_DEFAULT}"
INSTALL_DIR="${INSTALL_DIR_DEFAULT}"
PORT_TCP=443
PORT_UDP=443
PORT_UDP_ALT=8443
METRICS_ADDR="127.0.0.1"
METRICS_PORT=8080
ENABLE_METRICS=1
ENABLE_UFW=0
FORCE=0
DOMAIN=""
TLS_SERVER_NAME=""
CLIENT_ID="gateway-client"
CLIENT_SECRET=""
LOG_LEVEL="${LOG_LEVEL_DEFAULT}"
GO_BIN=""
PUBLIC_IPV4=""
PUBLIC_IPV6=""
SHOW_SECRETS=0

usage() {
  cat <<EOF
Usage: ${SCRIPT_NAME} [flags]

Flags:
  --repo <url>              Git repository URL (default: ${REPO_URL_DEFAULT})
  --ref <ref>               Git ref (branch/tag/commit, default: ${REF_DEFAULT})
  --go-version <ver>        Go version if install needed (default: ${GO_VERSION_DEFAULT})
  --install-dir <path>      Repo checkout directory (default: ${INSTALL_DIR_DEFAULT})
  --port-tcp <port>         Session TCP port (default: 443)
  --port-udp <port>         Session QUIC UDP port (default: 443)
  --port-udp-alt <port>     Optional UDP alt port redirected to --port-udp (default: 8443)
  --metrics-addr <addr>     Relay/metrics bind address (default: 127.0.0.1)
  --metrics-port <port>     Relay/metrics bind port (default: 8080)
  --no-metrics              Disable /metrics endpoint
  --ufw                     Open ports with UFW (only if UFW is installed+enabled)
  --domain <name>           Optional domain (for TLS cert SAN + metadata)
  --tls-server-name <sni>   Optional TLS server name (default: domain)
  --client-id <id>          HMAC client id (default: gateway-client)
  --secret <value>          HMAC secret (plain or b64:...); autogenerated if omitted
  --log-level <level>       Gateway log level (default: ${LOG_LEVEL_DEFAULT})
  --show-secrets            Print client id/secret in final summary
  --force                   Reinstall/overwrite existing installation
  -h, --help                Show help
EOF
}

log() {
  printf '[install] %s\n' "$*"
}

warn() {
  printf '[install][warn] %s\n' "$*" >&2
}

die() {
  local msg="$1"
  local code="${2:-1}"
  printf '[install][error] %s\n' "${msg}" >&2
  exit "${code}"
}

run() {
  log "run: $*"
  "$@"
}

require_root() {
  [[ "${EUID}" -eq 0 ]] || die "run as root: sudo bash ${SCRIPT_NAME} ..."
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1
}

valid_port() {
  [[ "$1" =~ ^[0-9]+$ ]] && (( "$1" >= 1 && "$1" <= 65535 ))
}

valid_ipv4() {
  local ip="$1"
  [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  local o
  IFS='.' read -r -a octets <<<"$ip"
  for o in "${octets[@]}"; do
    (( o >= 0 && o <= 255 )) || return 1
  done
  return 0
}

parse_flags() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --repo) REPO_URL="${2:-}"; shift 2 ;;
      --ref) REF="${2:-}"; shift 2 ;;
      --go-version) GO_VERSION="${2:-}"; shift 2 ;;
      --install-dir) INSTALL_DIR="${2:-}"; shift 2 ;;
      --port-tcp) PORT_TCP="${2:-}"; shift 2 ;;
      --port-udp) PORT_UDP="${2:-}"; shift 2 ;;
      --port-udp-alt) PORT_UDP_ALT="${2:-}"; shift 2 ;;
      --metrics-addr) METRICS_ADDR="${2:-}"; shift 2 ;;
      --metrics-port) METRICS_PORT="${2:-}"; shift 2 ;;
      --no-metrics) ENABLE_METRICS=0; shift ;;
      --ufw) ENABLE_UFW=1; shift ;;
      --domain) DOMAIN="${2:-}"; shift 2 ;;
      --tls-server-name) TLS_SERVER_NAME="${2:-}"; shift 2 ;;
      --client-id) CLIENT_ID="${2:-}"; shift 2 ;;
      --secret) CLIENT_SECRET="${2:-}"; shift 2 ;;
      --log-level) LOG_LEVEL="${2:-}"; shift 2 ;;
      --show-secrets) SHOW_SECRETS=1; shift ;;
      --force) FORCE=1; shift ;;
      -h|--help) usage; exit 0 ;;
      *) die "unknown flag: $1" ;;
    esac
  done
}

validate_flags() {
  [[ -n "${REPO_URL}" ]] || die "--repo cannot be empty"
  [[ -n "${REF}" ]] || die "--ref cannot be empty"
  [[ -n "${INSTALL_DIR}" ]] || die "--install-dir cannot be empty"
  [[ -n "${CLIENT_ID}" ]] || die "--client-id cannot be empty"
  [[ -n "${METRICS_ADDR}" ]] || die "--metrics-addr cannot be empty"
  [[ -n "${LOG_LEVEL}" ]] || die "--log-level cannot be empty"

  valid_port "${PORT_TCP}" || die "invalid --port-tcp: ${PORT_TCP}"
  valid_port "${PORT_UDP}" || die "invalid --port-udp: ${PORT_UDP}"
  valid_port "${PORT_UDP_ALT}" || die "invalid --port-udp-alt: ${PORT_UDP_ALT}"
  valid_port "${METRICS_PORT}" || die "invalid --metrics-port: ${METRICS_PORT}"
}

check_existing_installation() {
  local installed=0
  [[ -f "${SERVICE_FILE}" ]] && installed=1
  [[ -x "${BIN_PATH}" ]] && installed=1
  [[ -f "${ENV_FILE}" ]] && installed=1

  if [[ "${installed}" -eq 1 && "${FORCE}" -ne 1 ]]; then
    die "existing installation detected. Re-run with --force to overwrite." 2
  fi
}

install_dependencies() {
  local packages=(curl git ca-certificates openssl iproute2 iptables)
  if [[ "${ENABLE_UFW}" -eq 1 ]]; then
    packages+=(ufw)
  fi
  log "installing dependencies: ${packages[*]}"
  run apt-get update -y
  DEBIAN_FRONTEND=noninteractive run apt-get install -y "${packages[@]}"
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    *) die "unsupported architecture: $(uname -m)" ;;
  esac
}

go_version_ge() {
  local current="$1"
  local required="$2"
  local c_major c_minor c_patch r_major r_minor r_patch

  IFS='.' read -r c_major c_minor c_patch <<<"${current}"
  IFS='.' read -r r_major r_minor r_patch <<<"${required}"
  c_patch="${c_patch:-0}"
  r_patch="${r_patch:-0}"

  if (( c_major > r_major )); then return 0; fi
  if (( c_major < r_major )); then return 1; fi
  if (( c_minor > r_minor )); then return 0; fi
  if (( c_minor < r_minor )); then return 1; fi
  (( c_patch >= r_patch ))
}

ensure_go() {
  if need_cmd go; then
    local found raw ver
    found="$(command -v go)"
    raw="$("${found}" version | awk '{print $3}')"
    ver="${raw#go}"
    if go_version_ge "${ver}" "${GO_VERSION}"; then
      GO_BIN="${found}"
      log "using existing Go ${ver} (${GO_BIN})"
      return 0
    fi
    warn "found Go ${ver}, required >= ${GO_VERSION}; installing pinned Go ${GO_VERSION}"
  else
    log "Go not found; installing pinned Go ${GO_VERSION}"
  fi

  local arch tarball url tmp
  arch="$(detect_arch)"
  tarball="go${GO_VERSION}.linux-${arch}.tar.gz"
  url="https://go.dev/dl/${tarball}"
  tmp="/tmp/${tarball}"

  run curl -fL "${url}" -o "${tmp}"
  run rm -rf /usr/local/go
  run tar -C /usr/local -xzf "${tmp}"
  run rm -f "${tmp}"
  GO_BIN="/usr/local/go/bin/go"
  log "installed $(${GO_BIN} version)"
}

detect_public_ipv4() {
  local ip endpoint
  for endpoint in \
    "https://api.ipify.org" \
    "https://ifconfig.me/ip" \
    "https://ipv4.icanhazip.com"
  do
    ip="$(curl -4fsS --max-time 6 "${endpoint}" 2>/dev/null || true)"
    ip="$(printf '%s' "${ip}" | tr -d '[:space:]')"
    if valid_ipv4 "${ip}"; then
      printf '%s' "${ip}"
      return 0
    fi
  done

  ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}' || true)"
  ip="$(printf '%s' "${ip}" | tr -d '[:space:]')"
  if valid_ipv4 "${ip}"; then
    printf '%s' "${ip}"
    return 0
  fi
  return 1
}

detect_public_ipv6() {
  local ip endpoint
  for endpoint in \
    "https://api64.ipify.org" \
    "https://ifconfig.me/ip" \
    "https://ipv6.icanhazip.com"
  do
    ip="$(curl -6fsS --max-time 6 "${endpoint}" 2>/dev/null || true)"
    ip="$(printf '%s' "${ip}" | tr -d '[:space:]')"
    if [[ -n "${ip}" && "${ip}" == *:* ]]; then
      printf '%s' "${ip}"
      return 0
    fi
  done
  return 1
}

ensure_service_user() {
  if id -u "${SERVICE_USER}" >/dev/null 2>&1; then
    return 0
  fi
  log "creating system user ${SERVICE_USER}"
  run useradd --system --home /nonexistent --shell /usr/sbin/nologin --no-create-home "${SERVICE_USER}"
}

prepare_directories() {
  run mkdir -p "${CONFIG_DIR}"
  run mkdir -p "${INSTALL_DIR}"
}

prepare_repo() {
  if [[ -d "${INSTALL_DIR}/.git" ]]; then
    log "updating existing repo in ${INSTALL_DIR}"
    run git -c safe.directory="${INSTALL_DIR}" -C "${INSTALL_DIR}" remote set-url origin "${REPO_URL}"
    run git -c safe.directory="${INSTALL_DIR}" -C "${INSTALL_DIR}" fetch --tags --prune origin
    run git -c safe.directory="${INSTALL_DIR}" -C "${INSTALL_DIR}" checkout --force "${REF}"
    if git -c safe.directory="${INSTALL_DIR}" -C "${INSTALL_DIR}" rev-parse --verify "origin/${REF}" >/dev/null 2>&1; then
      run git -c safe.directory="${INSTALL_DIR}" -C "${INSTALL_DIR}" reset --hard "origin/${REF}"
    fi
  else
    log "cloning ${REPO_URL} -> ${INSTALL_DIR}"
    run rm -rf "${INSTALL_DIR}"
    run git clone "${REPO_URL}" "${INSTALL_DIR}"
    run git -c safe.directory="${INSTALL_DIR}" -C "${INSTALL_DIR}" checkout --force "${REF}"
  fi
  run chown -R "${SERVICE_USER}:${SERVICE_GROUP}" "${INSTALL_DIR}"
}

build_gateway_binary() {
  log "building gateway binary"
  (
    cd "${INSTALL_DIR}"
    CGO_ENABLED=0 "${GO_BIN}" build -buildvcs=false -trimpath -ldflags='-s -w' -o "${BIN_PATH}" ./cmd/gateway
  )
  run chown root:root "${BIN_PATH}"
  run chmod 0755 "${BIN_PATH}"
}

resolve_secret() {
  if [[ -n "${CLIENT_SECRET}" ]]; then
    return 0
  fi
  if [[ -f "${ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${ENV_FILE}" || true
    if [[ -n "${VLF_CLIENT_SECRET:-}" ]]; then
      CLIENT_SECRET="${VLF_CLIENT_SECRET}"
      return 0
    fi
  fi
  CLIENT_SECRET="$(openssl rand -base64 32 | tr -d '\r\n')"
}

yaml_escape_single() {
  printf '%s' "$1" | sed "s/'/''/g"
}

generate_self_signed_cert_if_needed() {
  if [[ -s "${CERT_FILE}" && -s "${KEY_FILE}" && "${FORCE}" -ne 1 ]]; then
    log "keeping existing TLS certificate: ${CERT_FILE}"
    return 0
  fi

  local cn san_value
  local -a san_items
  cn="${PUBLIC_IPV4}"
  [[ -n "${DOMAIN}" ]] && cn="${DOMAIN}"
  san_items=("DNS:localhost" "IP:127.0.0.1")
  [[ -n "${PUBLIC_IPV4}" ]] && san_items+=("IP:${PUBLIC_IPV4}")
  [[ -n "${PUBLIC_IPV6}" ]] && san_items+=("IP:${PUBLIC_IPV6}")
  [[ -n "${DOMAIN}" ]] && san_items+=("DNS:${DOMAIN}")
  if [[ -n "${TLS_SERVER_NAME}" && "${TLS_SERVER_NAME}" != "${DOMAIN}" ]]; then
    if valid_ipv4 "${TLS_SERVER_NAME}"; then
      san_items+=("IP:${TLS_SERVER_NAME}")
    else
      san_items+=("DNS:${TLS_SERVER_NAME}")
    fi
  fi
  san_value="$(IFS=, ; echo "${san_items[*]}")"

  log "generating self-signed certificate ${CERT_FILE}"
  run openssl req -x509 -newkey rsa:2048 -nodes -sha256 -days 825 \
    -keyout "${KEY_FILE}" \
    -out "${CERT_FILE}" \
    -subj "/CN=${cn}" \
    -addext "subjectAltName=${san_value}" >/dev/null 2>&1

  run chown root:"${SERVICE_GROUP}" "${KEY_FILE}" "${CERT_FILE}"
  run chmod 0640 "${KEY_FILE}"
  run chmod 0644 "${CERT_FILE}"
}

write_env_file() {
  local relay_base_ip relay_base_domain
  relay_base_ip="http://${PUBLIC_IPV4}:${METRICS_PORT}"
  relay_base_domain=""
  if [[ -n "${DOMAIN}" ]]; then
    relay_base_domain="http://${DOMAIN}:${METRICS_PORT}"
  fi

  cat > "${ENV_FILE}" <<EOF
VLF_REPO_URL=${REPO_URL}
VLF_REF=${REF}
VLF_INSTALL_DIR=${INSTALL_DIR}
VLF_CONFIG_FILE=${CONFIG_FILE}
VLF_CERT_FILE=${CERT_FILE}
VLF_KEY_FILE=${KEY_FILE}
VLF_PUBLIC_IPV4=${PUBLIC_IPV4}
VLF_PUBLIC_IPV6=${PUBLIC_IPV6}
VLF_DOMAIN=${DOMAIN}
VLF_TLS_SERVER_NAME=${TLS_SERVER_NAME}
VLF_PORT_TCP=${PORT_TCP}
VLF_PORT_UDP=${PORT_UDP}
VLF_PORT_UDP_ALT=${PORT_UDP_ALT}
VLF_METRICS_ADDR=${METRICS_ADDR}
VLF_METRICS_PORT=${METRICS_PORT}
VLF_ENABLE_METRICS=${ENABLE_METRICS}
VLF_LOG_LEVEL=${LOG_LEVEL}
VLF_PROTOCOL_ID=${PROTOCOL_ID_DEFAULT}
VLF_CLIENT_ID=${CLIENT_ID}
VLF_CLIENT_SECRET=${CLIENT_SECRET}
VLF_RELAY_BASE_IP=${relay_base_ip}
VLF_RELAY_BASE_DOMAIN=${relay_base_domain}
VLF_UDP_PPS_HOLD_SECONDS=3
EOF

  run chown root:root "${ENV_FILE}"
  run chmod 0600 "${ENV_FILE}"
}

write_config_file() {
  local metrics_enabled esc_client_id esc_client_secret
  metrics_enabled="false"
  [[ "${ENABLE_METRICS}" -eq 1 ]] && metrics_enabled="true"
  esc_client_id="$(yaml_escape_single "${CLIENT_ID}")"
  esc_client_secret="$(yaml_escape_single "${CLIENT_SECRET}")"

  cat > "${CONFIG_FILE}" <<EOF
listen_http: "${METRICS_ADDR}:${METRICS_PORT}"
listen_quic: "0.0.0.0:${PORT_UDP}"
listen_tcp: "0.0.0.0:${PORT_TCP}"
allow_insecure_http: true
enable_metrics: ${metrics_enabled}
protocol_id: "${PROTOCOL_ID_DEFAULT}"
log_level: "${LOG_LEVEL}"
max_dgram_payload: 1200

tls:
  cert_path: "${CERT_FILE}"
  key_path: "${KEY_FILE}"
  auto_generate: false

client_secrets:
  '${esc_client_id}': '${esc_client_secret}'

auth:
  clock_skew: "60s"
  replay_ttl: "60s"

limits:
  max_conns_per_client: 256
  max_total_conns: 8192
  max_bytes_per_minute_per_client: 268435456
  max_recv_window_bytes: 1048576
  relay_send_window_bytes: 262144
  max_flows_per_session: 512
  max_udp_pps: 5000
  session_datagram_workers: 8
  session_datagram_queue: 16384
  max_bytes_per_minute_per_session: 536870912
  session_up_kbps: 100000
  session_down_kbps: 100000

timeouts:
  relay_idle: "20s"
  session_idle: "60s"
  dial_timeout: "10s"
EOF

  run chown root:"${SERVICE_GROUP}" "${CONFIG_FILE}"
  run chmod 0640 "${CONFIG_FILE}"
}

write_systemd_unit() {
  local udp_alt_hooks=""
  local capability_bounding_set="CAP_NET_BIND_SERVICE"
  local ambient_capabilities="CAP_NET_BIND_SERVICE"
  if [[ "${PORT_UDP_ALT}" != "${PORT_UDP}" ]]; then
    capability_bounding_set="CAP_NET_BIND_SERVICE CAP_NET_ADMIN"
    ambient_capabilities="CAP_NET_BIND_SERVICE CAP_NET_ADMIN"
    udp_alt_hooks="$(cat <<EOF
ExecStartPre=/bin/bash -lc 'if command -v iptables >/dev/null 2>&1; then iptables -t nat -C PREROUTING -p udp --dport "${PORT_UDP_ALT}" -j REDIRECT --to-ports "${PORT_UDP}" 2>/dev/null || iptables -t nat -A PREROUTING -p udp --dport "${PORT_UDP_ALT}" -j REDIRECT --to-ports "${PORT_UDP}"; fi'
ExecStartPre=/bin/bash -lc 'if command -v iptables >/dev/null 2>&1; then iptables -t nat -C OUTPUT -p udp -d 127.0.0.1 --dport "${PORT_UDP_ALT}" -j REDIRECT --to-ports "${PORT_UDP}" 2>/dev/null || iptables -t nat -A OUTPUT -p udp -d 127.0.0.1 --dport "${PORT_UDP_ALT}" -j REDIRECT --to-ports "${PORT_UDP}"; fi'
ExecStopPost=/bin/bash -lc 'if command -v iptables >/dev/null 2>&1; then iptables -t nat -D PREROUTING -p udp --dport "${PORT_UDP_ALT}" -j REDIRECT --to-ports "${PORT_UDP}" >/dev/null 2>&1 || true; iptables -t nat -D OUTPUT -p udp -d 127.0.0.1 --dport "${PORT_UDP_ALT}" -j REDIRECT --to-ports "${PORT_UDP}" >/dev/null 2>&1 || true; fi'
EOF
)"
  fi

  cat > "${SERVICE_FILE}" <<EOF
[Unit]
Description=VLF Runtime Gateway
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${ENV_FILE}
PermissionsStartOnly=true
${udp_alt_hooks}
ExecStart=${BIN_PATH} -config ${CONFIG_FILE}
Restart=always
RestartSec=1
LimitNOFILE=1048576
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
ProtectControlGroups=true
ProtectKernelTunables=true
ProtectKernelModules=true
RestrictSUIDSGID=true
LockPersonality=true
MemoryDenyWriteExecute=true
SystemCallArchitectures=native
CapabilityBoundingSet=${capability_bounding_set}
AmbientCapabilities=${ambient_capabilities}
ReadWritePaths=${CONFIG_DIR}
UMask=0077

[Install]
WantedBy=multi-user.target
EOF
}

configure_ufw() {
  if [[ "${ENABLE_UFW}" -ne 1 ]]; then
    return 0
  fi

  if ! need_cmd ufw; then
    warn "ufw is not installed; skipping firewall rules"
    return 0
  fi
  if ! ufw status 2>/dev/null | grep -q '^Status: active'; then
    warn "ufw is not enabled; skipping firewall rules"
    return 0
  fi

  log "applying UFW rules"
  run ufw allow "${PORT_TCP}/tcp" >/dev/null
  run ufw allow "${PORT_UDP}/udp" >/dev/null
  if [[ "${PORT_UDP_ALT}" != "${PORT_UDP}" ]]; then
    run ufw allow "${PORT_UDP_ALT}/udp" >/dev/null
  fi
  if [[ "${ENABLE_METRICS}" -eq 1 && "${METRICS_ADDR}" != "127.0.0.1" && "${METRICS_ADDR}" != "::1" ]]; then
    run ufw allow "${METRICS_PORT}/tcp" >/dev/null
  fi
}

start_and_verify_service() {
  run systemctl daemon-reload
  run systemctl enable --now "${SERVICE_NAME}"
  sleep 1
  if ! systemctl is-active --quiet "${SERVICE_NAME}"; then
    journalctl -u "${SERVICE_NAME}" --no-pager -n 200 >&2 || true
    die "${SERVICE_NAME} failed to start"
  fi
}

post_checks() {
  log "post-check: systemctl status"
  systemctl status "${SERVICE_NAME}" --no-pager | sed -n '1,20p'

  log "post-check: listening sockets"
  ss -lntup | grep -E "(:${PORT_TCP}\\s|:${PORT_UDP}\\s|:${PORT_UDP_ALT}\\s|:${METRICS_PORT}\\s)" || true

  if [[ "${ENABLE_METRICS}" -eq 1 ]]; then
    log "post-check: metrics endpoint"
    if ! curl -fsS "http://127.0.0.1:${METRICS_PORT}/metrics" >/dev/null; then
      warn "metrics check failed on 127.0.0.1:${METRICS_PORT} (verify --metrics-addr and service logs)"
    fi
  fi
}

print_summary() {
  local domain_line sni_line service_state
  domain_line="(not configured; IP-only mode)"
  sni_line="(not required)"
  [[ -n "${DOMAIN}" ]] && domain_line="${DOMAIN}"
  [[ -n "${TLS_SERVER_NAME}" ]] && sni_line="${TLS_SERVER_NAME}"
  service_state="$(systemctl is-active "${SERVICE_NAME}" 2>/dev/null || true)"

  echo
  echo "================= VLF-PROTO INSTALL SUMMARY ================="
  echo "Public IPv4:      ${PUBLIC_IPV4}"
  echo "Public IPv6:      ${PUBLIC_IPV6:-n/a}"
  echo "Domain:           ${domain_line}"
  echo "TLS server name:  ${sni_line}"
  echo "Service:          ${SERVICE_NAME}"
  echo "Binary:           ${BIN_PATH}"
  echo "Repo dir:         ${INSTALL_DIR}"
  echo "Config file:      ${CONFIG_FILE}"
  echo "Env file:         ${ENV_FILE}"
  echo "Service status:   ${service_state:-unknown}"
  echo "Ports:            tcp=${PORT_TCP} udp=${PORT_UDP} udp-alt=${PORT_UDP_ALT}"
  echo "Relay bind:       ${METRICS_ADDR}:${METRICS_PORT}"
  if [[ "${ENABLE_METRICS}" -eq 1 ]]; then
    echo "Metrics:          enabled (http://127.0.0.1:${METRICS_PORT}/metrics)"
  else
    echo "Metrics:          disabled"
  fi
  if [[ "${SHOW_SECRETS}" -eq 1 ]]; then
    echo
    echo "Secrets:"
    echo "  VLF_CLIENT_ID=${CLIENT_ID}"
    echo "  VLF_CLIENT_SECRET=${CLIENT_SECRET}"
  else
    echo
    echo "Secrets:          hidden (use --show-secrets to print)"
  fi
  echo "=============================================================="
}

main() {
  parse_flags "$@"
  require_root
  validate_flags
  check_existing_installation

  install_dependencies
  ensure_go

  PUBLIC_IPV4="$(detect_public_ipv4 || true)"
  [[ -n "${PUBLIC_IPV4}" ]] || die "failed to detect public IPv4"
  PUBLIC_IPV6="$(detect_public_ipv6 || true)"

  if [[ -n "${DOMAIN}" && -z "${TLS_SERVER_NAME}" ]]; then
    TLS_SERVER_NAME="${DOMAIN}"
  fi

  ensure_service_user
  prepare_directories
  resolve_secret
  prepare_repo
  build_gateway_binary
  generate_self_signed_cert_if_needed
  write_env_file
  write_config_file
  write_systemd_unit
  configure_ufw
  start_and_verify_service
  post_checks
  print_summary
}

main "$@"
